# Generated by Django 5.2.2 on 2025-06-10 18:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('comment', models.CharField(blank=True, max_length=150, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Кухонный инструмент',
                'verbose_name_plural': 'Кухонные инструменты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DishProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Количество')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_name_per_dish',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='dish',
            name='presentation',
            field=models.CharField(choices=[('delicatessen', 'Холодные закуски'), ('hot_appetizers', 'Горячие закуски'), ('first course', 'Первое блюдо: суп'), ('main_dish', 'Горячее'), ('dessert', 'Десерт'), ('beverages', 'Напитки'), ('other', 'Иное')], default='delicatessen', max_length=35, verbose_name='Подача блюда'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_product_name'),
        ),
        migrations.AddField(
            model_name='cookingtool',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dish',
            name='cooking_tools',
            field=models.ManyToManyField(blank=True, related_name='tools_dishes', to='app.cookingtool', verbose_name='Кухонные инструменты'),
        ),
        migrations.AddField(
            model_name='dishproduct',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dish', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='dishproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='dishproduct',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unit', verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='dishproduct',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dish',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products_dishes', through='app.DishProduct', to='app.product'),
        ),
        migrations.AddConstraint(
            model_name='cookingtool',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_tool_name'),
        ),
    ]
