# Generated by Django 5.2.2 on 2025-06-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dishproduct_options_remove_dishproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='presentation',
            field=models.CharField(choices=[('delicatessen', 'Холодные закуски'), ('hot_appetizers', 'Горячие закуски'), ('first_course', 'Первое блюдо: суп'), ('main_dish', 'Горячее'), ('dessert', 'Десерт'), ('beverages', 'Напитки'), ('other', 'Иное')], default='delicatessen', max_length=35, verbose_name='Подача блюда'),
        ),
    ]
